# Generated by Django 4.1.5 on 2023-01-12 01:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0004_remove_chatroom_creator_chatroom_members'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChatRoom',
            new_name='Room',
        ),
    ]
